Repository fluent/fluentd, pull requests merged in 2018-03, with the labels that each got.

#1875 parser_json: Add EncodingError to rescue list for oj 3.x. fix #1866
  lib/fluent/plugin/parser_json.rb
Labels: bug

#1874 buf_file: Skip and delete broken file chunks during resume. fix #1760
  lib/fluent/plugin/buf_file.rb
  lib/fluent/plugin/buffer/file_chunk.rb
  test/plugin/test_buf_file.rb
Labels: bug, v1

#1861 Add support for TLS Mutual authentication within forward input
  lib/fluent/plugin_helper/cert_option.rb
  lib/fluent/plugin_helper/server.rb
Labels: enhancement, v1

#1883 Fix boolean parameters without value with following comment
  lib/fluent/config/types.rb
  test/config/test_plugin_configuration.rb
Labels: bug

#1893 out_forward: Fix race condition with <security> on multi thread environment. fix #1878
  lib/fluent/plugin/out_forward.rb
  test/plugin/test_out_forward.rb
Labels: bug, v1

#1901 output: Prevent flushing threads from consuming too much CPU.
  lib/fluent/plugin/output.rb
Labels: bug, v1
