Repository fluent/fluentd, pull requests merged in 2018-04, with the labels that each got.

#1919 Delete empty queued_num field after purging chunks
  lib/fluent/plugin/buffer.rb
Labels: bug, v1

#1916 buffer: Add queued_chunks_limit_size to control the number of queued chunks
  lib/fluent/plugin/buffer.rb
  lib/fluent/plugin/output.rb
  test/plugin/test_output_as_buffered_retries.rb
Labels: enhancement, v1

#1925 out_forward: The node should be disabled when TLS socket for ack returns an error. Fix #1923
  lib/fluent/plugin/out_forward.rb
Labels: bug, v1

#1940 filter_grep: Improve the performance
  lib/fluent/plugin/filter_grep.rb
Labels: enhancement, v1

#1942 Close invalid socket when ssl error happens on reading. fix #1924
  lib/fluent/plugin_helper/server.rb
Labels: bug, v1

#1947 retry_state: Fix exponential backoff with too big steps. fix #1937
  lib/fluent/plugin_helper/retry_state.rb
  test/plugin_helper/test_retry_state.rb
Labels: bug, v1

#1957 Resolve unexpected exit on SIGUSR1
  lib/fluent/log.rb
  lib/fluent/supervisor.rb
Labels: bug, v1

#1952 output: Add backup feature for bad chunks
  lib/fluent/env.rb
  lib/fluent/plugin/output.rb
  test/plugin/test_output_as_buffered_backup.rb
Labels: feature request, v1
