Repository fluent/fluentd, pull requests merged in 2018-11, with the labels that each got.

#2165 Fix deadlock between on_writable and close
  lib/fluent/plugin/in_forward.rb
  lib/fluent/plugin/out_forward.rb
  lib/fluent/plugin_helper/server.rb
Labels: v1

#2147 in_syslog: Support octet counting frame. fix #1679
  lib/fluent/plugin/in_syslog.rb
  test/plugin/test_in_syslog.rb
Labels: enhancement, v1

#2169 Check secondary type to avoid unexpected error. fix #2167
  lib/fluent/plugin/output.rb
  test/plugin/test_output.rb
Labels: bug, v1

#2170 Remove `Thread#run` to avoid unexpected interruption.
  lib/fluent/plugin/output.rb
Labels: bug, v1

#2173 Use flush_thread_count value for queued_chunks_limit_size when queued_chunks_limit_size is not specified
  lib/fluent/plugin/buffer.rb
  lib/fluent/plugin/output.rb
  test/plugin/test_buffer.rb
  test/plugin/test_output_as_buffered.rb
  test/plugin/test_output_as_buffered_retries.rb
  test/plugin/test_output_as_buffered_secondary.rb
Labels: enhancement, v1

#2184 Add connection check at startup when out_forward.
  lib/fluent/plugin/out_forward.rb
  test/plugin/test_out_forward.rb
Labels: enhancement, v1

#2190 out_forward: Separate parameter names for certificates
  lib/fluent/plugin/out_forward.rb
  test/plugin/test_out_forward.rb
Labels: enhancement, v1
