Repository fluent/fluentd, pull requests merged in 2019-10, with the labels that each got.

#2541 out_forward plugin can set targets dynamically via service discovery plugin.
  example/out_forward_sd.conf
  example/sd.yaml
  lib/fluent/plugin.rb
  lib/fluent/plugin/out_forward.rb
  lib/fluent/plugin/out_forward/load_balancer.rb
  lib/fluent/plugin/sd_file.rb
  lib/fluent/plugin/sd_static.rb
  lib/fluent/plugin/service_discovery.rb
  lib/fluent/plugin_helper.rb
  lib/fluent/plugin_helper/service_discovery.rb
  lib/fluent/plugin_helper/service_discovery/manager.rb
  lib/fluent/plugin_helper/service_discovery/round_robin_balancer.rb
  test/plugin/data/sd_file/config
  test/plugin/data/sd_file/config.json
  test/plugin/data/sd_file/config.yaml
  test/plugin/data/sd_file/config.yml
  test/plugin/data/sd_file/invalid_config.yml
  test/plugin/test_out_forward.rb
  test/plugin/test_sd_file.rb
  test/plugin_helper/service_discovery/test_manager.rb
  test/plugin_helper/service_discovery/test_round_robin_balancer.rb
  test/plugin_helper/test_service_discovery.rb
Labels: enhancement, feature request

#2643 formatter_csv: support nested fields. fix #2630
  lib/fluent/plugin/formatter_csv.rb
  lib/fluent/plugin_helper/record_accessor.rb
  test/plugin/test_formatter_csv.rb
Labels: enhancement

#2649 child_process helper: fix stderr blocking for discard case. fix #2609
  lib/fluent/plugin_helper/child_process.rb
  test/plugin_helper/test_child_process.rb
Labels: bug

#2660 record_accessor: Make code simple and bit faster
  lib/fluent/plugin_helper/record_accessor.rb
Labels: enhancement
