Repository fluent/fluentd, pull requests merged in 2019-07, with the labels that each got.

#2482 Avoid zero division error when there are no available nodes
  lib/fluent/plugin/out_forward.rb
  test/plugin/test_out_forward.rb
Labels: bug

#2487 socket: Support all private keys OpenSSL supports
  lib/fluent/command/ca_generate.rb
  lib/fluent/plugin_helper/cert_option.rb
  lib/fluent/plugin_helper/socket.rb
Labels: enhancement

#2491 Improve stats method
  lib/fluent/plugin/buffer.rb
  lib/fluent/plugin/output.rb
Labels: enhancement

#2479 Update tzinfo to v2
  fluentd.gemspec
  lib/fluent/time.rb
  lib/fluent/timezone.rb
  test/test_time_formatter.rb
Labels: enhancement

#2513 parser: Add timeout parameter to avoid parsing stuck. fix #2464
  lib/fluent/error.rb
  lib/fluent/plugin/parser.rb
  test/plugin/test_parser.rb
Labels: enhancement

#2524 buf_file: Add path_suffix parameter. ref #2236
  lib/fluent/plugin/buf_file.rb
  test/plugin/test_buf_file.rb
Labels: enhancement

#2488 Add HTTP output plugin
  lib/fluent/plugin/out_http.rb
  test/plugin/test_out_http.rb
Labels: feature request

#2529 formatter_csv: Improve the performance. 2x faster
  lib/fluent/plugin/formatter_csv.rb
  test/plugin/test_formatter_csv.rb
Labels: enhancement
