Repository fluent/fluentd, pull requests merged in 2019-03, with the labels that each got.

#2324 out_forward: Add secret to tls_client_private_key_passphrase
  lib/fluent/plugin/out_forward.rb
Labels: enhancement

#2321 system: Add worker_id to process_name when workers is larger than 1
  lib/fluent/supervisor.rb
Labels: enhancement

#2331 parser_regexp: Check named capture. ref #2330
  lib/fluent/plugin/parser_regexp.rb
  test/compat/test_parser.rb
  test/plugin/test_parser_regexp.rb
Labels: enhancement

#2343 Expose the current list of timekeys as a buffer metric
  lib/fluent/plugin/buffer.rb
  lib/fluent/plugin/in_monitor_agent.rb
  test/plugin/test_buffer.rb
  test/plugin/test_in_monitor_agent.rb
Labels: enhancement, v1

#2347 in_tcp/in_udp: Add source_address_key parameter
  lib/fluent/plugin/in_tcp.rb
  lib/fluent/plugin/in_udp.rb
  test/plugin/test_in_tcp.rb
  test/plugin/test_in_udp.rb
Labels: enhancement, v1

#2353 out_file: Create directory for symlink. fix #2346
  lib/fluent/plugin/out_file.rb
  test/plugin/test_out_file.rb
Labels: bug, v1
