Repository fluent/fluentd, pull requests merged in 2019-02, with the labels that each got.

#2276 output: Work retry_forever and <secondary> together. fix #2257
  lib/fluent/plugin/output.rb
  lib/fluent/plugin_helper/retry_state.rb
  test/plugin/test_output_as_buffered_retries.rb
Labels: enhancement, v1

#2254 out_file: Support placeholders in symlink_path parameter
  lib/fluent/plugin/out_file.rb
  test/plugin/test_out_file.rb
Labels: enhancement, v1

#2291 Reduce delay before flush when large timekey and small timekey_wait a…
  lib/fluent/plugin/output.rb
  test/plugin/test_output_as_buffered.rb
Labels: enhancement, v1

#2301 output: Add MessagePack::UnpackError to unrecoverable case
  lib/fluent/plugin/output.rb
  test/plugin/test_output_as_buffered_backup.rb
Labels: bug

#2305 in_tail encoding enhancement
  lib/fluent/plugin/in_tail.rb
  test/plugin/test_in_tail.rb
Labels: enhancement, v1

#2310 Add more errors to ignore list in UDP socket
  lib/fluent/plugin_helper/server.rb
Labels: bug, v1

#2292 Support multi workers assign syntax on `<worker>` section. Fix #2289
  lib/fluent/config/element.rb
  lib/fluent/plugin/base.rb
  lib/fluent/root_agent.rb
  test/config/test_element.rb
  test/test_root_agent.rb
Labels: v1
