Repository fluent/fluentd, pull requests merged in 2019-05, with the labels that each got.

#2393 Keepalive for out_forward plugin
  lib/fluent/plugin/out_forward.rb
  test/plugin/test_out_forward.rb
Labels: feature request, v1

#2409 Improve storage local plugin
  lib/fluent/plugin/storage_local.rb
Labels: enhancement

#2395 Use server helper in in_http
  lib/fluent/plugin/in_http.rb
Labels: v1
