Repository fluent/fluentd, pull requests merged in 2019-08, with the labels that each got.

#2535 parser_csv: Improve the performance for typical cases
  lib/fluent/plugin/parser_csv.rb
  test/plugin/test_parser_csv.rb
Labels: enhancement

#2547 fix data lost on decompression
  lib/fluent/plugin/compressable.rb
Labels: bug

#2565 OneEvent isn't always empty
  lib/fluent/event.rb
Labels: enhancement

#2561 Use Mutex instead of Monitor
  lib/fluent/compat/output.rb
  lib/fluent/plugin/bare_output.rb
  lib/fluent/plugin/multi_output.rb
  lib/fluent/plugin/output.rb
Labels: enhancement

#2567 in_tcp: Improve the performance for multiple events case
  lib/fluent/plugin/in_tcp.rb
  test/plugin/test_in_tcp.rb
Labels: enhancement

#2557 Use faster way to get sec and nsec
  lib/fluent/clock.rb
  lib/fluent/plugin/buffer/chunk.rb
  lib/fluent/plugin/buffer/file_chunk.rb
  lib/fluent/plugin/buffer/memory_chunk.rb
  lib/fluent/plugin/output.rb
  lib/fluent/time.rb
  test/helper.rb
  test/helpers/process_extenstion.rb
Labels: enhancement

#2551 Not to call IO#truncate to avoid too many IO flush
  lib/fluent/plugin/buffer/file_chunk.rb
  test/plugin/test_buf_file.rb
  test/plugin/test_buffer_file_chunk.rb
Labels: enhancement

#2563 Remove `@metadata_list` from buffer.rb
  lib/fluent/plugin/buffer.rb
  lib/fluent/plugin/out_file.rb
  lib/fluent/plugin/output.rb
  test/plugin/test_buffer.rb
Labels: enhancement

#2559 Cache msgpack packer/unpacker
  lib/fluent/event.rb
  lib/fluent/event_router.rb
  lib/fluent/msgpack_factory.rb
  lib/fluent/plugin/buffer/file_chunk.rb
  lib/fluent/plugin/output.rb
Labels: enhancement

#2564 Add option to check queued? loosely
  lib/fluent/plugin/buffer.rb
  lib/fluent/plugin/output.rb
Labels: enhancement

#2579 Add buf_file_single plugin
  lib/fluent/plugin/buf_file_single.rb
  lib/fluent/plugin/buffer/file_single_chunk.rb
  test/plugin/test_buf_file_single.rb
  test/plugin/test_buffer_file_single_chunk.rb
Labels: feature request

#2560 Add hash method to metadata to speed up comparing it in a hash key
  lib/fluent/plugin/buffer.rb
Labels: enhancement
