Repository fluent/fluentd, pull requests merged in 2025-03, with the labels that each got.

#4846 test: fix Sigdump tests failure
  test/test_supervisor.rb
Labels: backport to LTS, CI

#4850 Backport(v1.16) test: fix Sigdump tests failure (#4846)
  test/test_supervisor.rb
Labels: CI

#4848 parser: use URI#open instead of URI.open
  lib/fluent/config/parser.rb
Labels: backport to LTS

#4854 v1_parser: use URI#open instead of URI.open
  lib/fluent/config/v1_parser.rb
Labels: backport to LTS

#4847 test: improve Sigdump test for Windows
  test/test_supervisor.rb
Labels: backport to LTS, CI

#4845 memory_chunk: clear internal memory use in buffer string
  lib/fluent/plugin/buffer/memory_chunk.rb
  test/plugin/test_output_as_buffered_compress.rb
Labels: memory

#4862 Backport(v1.16) test: improve Sigdump test for Windows (#4847)
  test/test_supervisor.rb
Labels: CI

#4869 Add fiddle as dependency gem for Ruby 3.5 on Windows
  fluentd.gemspec
Labels: CI

#4864 formatter_csv: fix memory leak
  lib/fluent/compat/formatter.rb
  lib/fluent/plugin/formatter_csv.rb
Labels: backport to LTS

#4874 test_in_tail: add wait to detect rotation
  test/plugin/test_in_tail.rb
Labels: backport to LTS, CI

#4877 test_output_as_buffered_retries: fix flaky test
  test/plugin/test_output_as_buffered_retries.rb
Labels: CI
