Repository fluent/fluentd, pull requests merged in 2025-01, with the labels that each got.

#4755 test_out_exec_filter: add a sleep to ensure the stream is emitted
  test/plugin/test_out_exec_filter.rb
Labels: backport to LTS, CI

#4782 Windows: Fix an issue where stopping the service immediately after startup could leave the processes
  lib/fluent/winsvc.rb
Labels: backport to LTS

#4804 ci: remove latest setting for rubygems
  .github/workflows/test.yml
Labels: CI
