Repository fluent/fluentd, pull requests merged in 2025-05, with the labels that each got.

#4954 winsvc: Fix bug where service accidentally stops after starting
  .github/workflows/test.yml
  lib/fluent/winsvc.rb
  test/scripts/windows_service_test.ps1
Labels: backport to LTS

#4901 test: add in_http multipart test case
  lib/fluent/test/helpers.rb
  test/plugin/test_in_http.rb
Labels: CI

#4859 out_http: TLS1.3 support
  lib/fluent/plugin/out_http.rb
  lib/fluent/tls.rb
  test/plugin/test_out_http.rb
  test/test_tls.rb
Labels: enhancement
